package org.jbpm.recobros;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class Formula  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.util.List<org.jbpm.recobros.Medicamento> lista_medicamentos;

    public Formula() {
    }

    public Formula(java.util.List<org.jbpm.recobros.Medicamento> lista_medicamentos) {
        this.lista_medicamentos = lista_medicamentos;
    }


    
    public java.util.List<org.jbpm.recobros.Medicamento> getLista_medicamentos() {
        return this.lista_medicamentos;
    }

    public void setLista_medicamentos(  java.util.List<org.jbpm.recobros.Medicamento> lista_medicamentos ) {
        this.lista_medicamentos = lista_medicamentos;
    }
}